name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNmY1ZmM2MzEtMzgzYy00MTc3LTgxMTktM2E3ZDYwMDNhNmIxIiwidGVuYW50X2lkIjoiY2YwMzA2OWM4MjY1MTIyZjVjZGE3Y2NlYTY4NGQxNjJhYjlkNWExMzUzMDQ5NTZmNmE3NjczODA4ZjFmMWE5YiIsImludGVybmFsX3NlY3JldCI6ImRhYzU3ZTBkLWEyN2YtNDQ4Ni04OTQyLTFlNTc5Y2ZlNTUwNSJ9.7VDUrNl-JcQeDn08Ohtn2NwxCBy7VZSnttV6uRUyNhQ"

# [vars]
# MY_VARIABLE = "production_value"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
